### ISSUE TITLE
Spindle button without impact

### ISSUE THREAD

**Issue by JensInternal** [bdring/FluidNC#185]
Please only submit bugs for the **latest** version of the code. You can check the version number in the startup messages.

Please provide the [FluidNC boot messages per this page](https://github.com/bdring/FluidNC/wiki/Requesting-Help#fluidnc-boot-messages).
```[MSG:INFO: FluidNC v3.2.7]
[MSG:INFO: Compiled with ESP32 SDK:v3.3.5-1-g85c43024c]
[MSG:INFO: Configuration file:config.yaml]
[MSG:INFO: Machine ESP32 Jens production]
[MSG:INFO: Board ESP32 Jens production]
[MSG:INFO: SPI SCK:gpio.18 MOSI:gpio.23 MISO:gpio.19]
[MSG:INFO: SD Card cs_pin:gpio.5 dectect:NO_PIN]
[MSG:INFO: Stepping:RMT Pulse:10us Dsbl Delay:0us Dir Delay:0us Idle Delay:250ms]
[MSG:INFO: Axis count 3]
[MSG:INFO: Shared stepper disable gpio.13:low]
[MSG:INFO: Axis X (-850.000,150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     Standard Stepper Step:gpio.12 Dir:gpio.14 Disable:NO_PIN]
[MSG:INFO:     Pos Limit gpio.17:pu]
[MSG:INFO: Axis Y (150.000,575.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     Standard Stepper Step:gpio.26 Dir:gpio.15:low Disable:NO_PIN]
[MSG:INFO:     Pos Limit gpio.4:pu]
[MSG:INFO: Axis Z (30.000,150.000)]
[MSG:INFO:   Motor0]
[MSG:INFO:     Standard Stepper Step:gpio.27 Dir:gpio.33 Disable:NO_PIN]
[MSG:INFO:     Pos Limit gpio.16:pu]
[MSG:INFO: Reset gpio.34:low]
[MSG:INFO: FeedHold gpio.36:low]
[MSG:INFO: CycleStart gpio.39:low]
[MSG:INFO: Kinematic system: Cartesian]
[MSG:INFO: Relay Spindle Ena:NO_PIN Out:gpio.32 Dir:NO_PIN]
[MSG:INFO: Using spindle Relay]
[MSG:INFO: Flood coolant gpio.2]
[MSG:INFO: Probe Pin: gpio.35]
[MSG:INFO: Connecting to STA SSID:Home]
[MSG:INFO: Connecting.]
[MSG:INFO: Connecting..]
[MSG:INFO: Connected - IP is 192.168.2.30]
[MSG:INFO: WiFi on]
[MSG:INFO: Start mDNS with hostname:http://fluidnc.local/]
[MSG:INFO: SSDP Started]
[MSG:INFO: HTTP started on port 80]
[MSG:INFO: Telnet started on port 23]

Grbl 3.2 [FluidNC v3.2.7 (wifi) '$' for help]```

Is the problem repeatable?
yes

Under what conditions does the bug occur?
Manual click in the web interface on "Spindle" button shows no effect, same with M3.
"S<any number> M3" (on) and "S0 M3" (off) works in NC file and in command line.

Preferred behaviour is that relay spindles should be switched on/off by button, too.

**Comment by MitchBradley** [comment]
The WebUI code is a separate project from a different developer so we did not define its core behavior.  That said, we have made some mods to make it work better with FluidNC so I guess we "own" it to some extent - but we hope to switch over to Luc's shiny new version whenever it is ready.

The intention of that button, based on looking at the WebUI source code, is not to turn on the spindle, but rather to issue the Grbl "spindle override stop" realtime command.  Spindle stop override is a feature that first appeared in grbl 1.1.  It is rather poorly documented on the Grbl wiki, but it appears to be for the purpose of turning off the spindle during a feedhold. as that realtime character (0x9e) is ignored except in HOLD state.

Adding a WebUI button to turn the spindle on and off would require some careful design, since the only way to force the spindle on is to issue "M3 S<nonzero>" or "M4 S<nonzero>.  The issues are
1. What is the appropriate S value to use?  Obviously for your relay spindle any nonzero value is okay, but that would not work for everybody, so there would need to be some way to set the S value, and possibly some way to configure its persistence.
2. For completeness, there would need to be both CW (M3) and CCW (M4) buttons, or otherwise some way to choose the direction.
3. It would not be safe to issue M3 or M4 from the UI during the running of a job, so there would need to be some coordination with the overall execution state.  FluidNC/Grbl_Esp32 will reject the command if the state is not IDLE, so part of that coordination is already in place, but ideally there would be appropriate feedback to make it clear to the user what is happening.

Simply repurposing the button is problematic for people who are accustomed to its existing behavior; it could cause an unsafe spindle turn-on.  Making a feature that works only for relay spindles just invites the next bug report from somebody who has a different spindle type.

Summary: It is not nearly as easy as the problem statement seems to imply.
