### ISSUE TITLE
CNC ATC Esp32 fluidNc

### ISSUE THREAD

**Issue by Althafzahra** [bdring/FluidNC#361]
excuse me, I'm interested in making a CNC ATC like in the Barton dring video, is there any reference I can learn to make a cnc atc?  Thank you.
![20220403_193418](https://user-images.githubusercontent.com/90569123/161428407-2227519f-66e8-469c-8055-548ccecad781.jpg)

**Comment by RigoWeb** [comment]
Hi Barton & all,

I have built a similar ATC (but without tool measurement and with a stepper instead of a pneumatic cylinder). Therefore I've took a look to your branch ATC_Experiments. This looks very interesting to me, especially the idea to take tool positions etc. in config.yaml so that no compilation is required. It would be really great if this feature can be merged to main branch in the future :-)

Best regards and one more big thank you for your effort!!!

Chris
