### ISSUE TITLE
FluidNC-v3.4.3-posix

### ISSUE THREAD

**Issue by klspstck** [bdring/FluidNC#365]
I just re-started a project to re-animate a canibalized Stepcraft CNC.

Mechanics are done.

Electronics are similar to the 6-pack hardware, but a different form factor, EURO-Board 160mm X 100mm.
Fits better into off the shelf haousings.
Processor is ESP32 using I2S with 74xxx595 and Steckstick TMC2209 motor drivers.

FluidNC looks to me as the most suitable solution. Thank you for that.

Anyhow, even when just starting I had a couple of issues I want to share.

First, I am using Ubuntu LTS.

Downloading "fluidnc-v3.4.3-posix" didn't cause any problems.

I am adding now all steps I executed plus my solutions.
*****
fluidnc-v3.4.3-posix$ ./install-wifi.sh 
esptool.py --chip esp32 --baud 230400 dump_mem 0x3ff5a018 4 SecurityFuses.bin
esptool.py v3.2
Found 2 serial ports
Serial port /dev/ttyUSB0
Connecting....
Chip is ESP32-D0WD (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 78:e3:6d:de:8c:d8
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 230400
Changed.
Read 4 bytes
Done!
Hard resetting via RTS pin...
esptool.py --chip esp32 --baud 230400 --before default_reset --after hard_reset write_flash -z --flash_mode dio --flash_freq 80m --flash_size detect 0x1000 common/bootloader_dio_80m.bin 0xe000 common/boot_app0.bin 0x10000 wifi/firmware.bin 0x8000 wifi/partitions.bin
esptool.py v3.2
Found 2 serial ports
Serial port /dev/ttyUSB0
Connecting....
Chip is ESP32-D0WD (revision 1)
Features: WiFi, BT, Dual Core, 240MHz, VRef calibration in efuse, Coding Scheme None
Crystal is 40MHz
MAC: 78:e3:6d:de:8c:d8
Uploading stub...
Running stub...
Stub running...
Changing baud rate to 230400
Changed.
Configuring flash size...
Auto-detected Flash size: 4MB
Flash will be erased from 0x00001000 to 0x00005fff...
Flash will be erased from 0x0000e000 to 0x0000ffff...
Flash will be erased from 0x00010000 to 0x0015ffff...
Flash will be erased from 0x00008000 to 0x00008fff...
Compressed 17120 bytes to 11164...
Wrote 17120 bytes (11164 compressed) at 0x00001000 in 0.7 seconds (effective 195.6 kbit/s)...
Hash of data verified.
Compressed 8192 bytes to 47...
Wrote 8192 bytes (47 compressed) at 0x0000e000 in 0.1 seconds (effective 808.0 kbit/s)...
Hash of data verified.
Compressed 1375216 bytes to 796663...
Wrote 1375216 bytes (796663 compressed) at 0x00010000 in 35.7 seconds (effective 307.8 kbit/s)...
Hash of data verified.
Compressed 3072 bytes to 129...
Wrote 3072 bytes (129 compressed) at 0x00008000 in 0.1 seconds (effective 312.4 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
Starting fluidterm
Traceback (most recent call last):
  File "common/fluidterm.py", line 32, in <module>
    import serial
ModuleNotFoundError: No module named 'serial'

*****
putty can connect

*****

web gui:

File index.html.gz is missing, please upload it

executing 

  $ ./install-fs.sh 
  
solves this problem

*****

fluidterm can be started viy python direct.

$ python ./common/fluidterm.py 

--- Available ports:
---  1: /dev/ttyS0           'ttyS0'
---  2: /dev/ttyUSB0         'CP2102N USB to UART Bridge Controller'
--- Enter port index or full name: 2
--- Fluidterm on /dev/ttyUSB0  115200,8,N,1 ---
--- Quit: Ctrl+] | Upload: Ctrl+U | Reset: Ctrl+R ---
$
[HLP:$$ $+ $# $S $L $G $I $N $x=val $Nx=line $J=line $SLP $C $X $H $F $E=err ~ ! ? ctrl-x]
ok

After entering "$" the screen is converted from "black on white" to "white on black".

***** 
These things are really minor quircks.

****************************************************
What is more important to me is missing information.

I am well aware about the wiki and it is way better as others, especially those from our chinese friends.

And I also recognize "work in progress".

What am I missing:

More clearly description of config file parameter.
Example:
  disable_pin: i2so.3

"disable" usually is high significant, if the input is high, the part is disabled, else the part is enbled.

The tmc2209 has an "enable-" pin, the signal is low significant.

I am used to this since 1967, when starting to develop electronics.

My personal confusion is, will the disable pin act as an "enable-" when I am specifying

  disable_pin: i2so.3.low

?

Where in the sources can a find details about that?

Has the wiki been updated meanwhile?

I am now starting to create a config file, which hopefully will do waht I want to have.

By the way, the idea with that config file is really good. Congratiulation.

That's it in the moment.
Kind regards
Klaus P. Stock

**Comment by bdring** [comment]
The wiki has close to 700 commits. It is typically updated several times per week.

The original Grbl firmware used the term "disable" rather than enable. We kept that term. Many stepper driver modules including the TMC2209 have an "Enable Not" pin. This mean the active state is disable. 

You can set the [active state](https://github.com/bdring/FluidNC/wiki/FluidNC-Setting-Up-I-O-Pins#output-pin-attributes) of any output pin to high or low.

**Comment by MitchBradley** [comment]
Regarding:
> import serial
> ModuleNotFoundError: No module named 'serial'

In tools.sh, line 21 is supposed to install pyserial, thus making it possible to later import the serial module.  That line reads
```
  if ! python3 -m pip install xmodem pyserial; then
```
That works for the Linux installations that we have tried so far, but it seems to be failing in your setup.  I don't know why.  Linux and Python are extremely difficult, bordering on impossible, for us to support well, because there is an almost infinite number of variations.  Everything that we try works in some setups and fails in others.  The "venv" method that we use to manage Python and its modules is considered to be "best practices".

Regarding:
> File index.html.gz is missing, please upload it
> executing  $ ./install-fs.sh   solves this problem

The need to install index.html.gz is mentioned in various places in the documentation.  The difficulty in general with documentation is that there is no was to guarantee that an individual will read any of it, and if they do, that they will happen to find the part they need early enough to prevent problems.  Simply adding more text can be counterproductive, making it so long that it decreases the chances of people reading it.  If you know of a way to organize the docs better, we would welcome someone taking over that task.

**Comment by klspstck** [comment]
Good morning Mitch,

"because there is an almost infinite number of variations" that's the blessing and the curse of opensource software. ;-))

Unfortunately, I am engaged in another project doing documentation, therefor my time is quite limited.

I am doing a couple of things for myself, maybe I am forwarding this stuff to you later.

By the way, the axes are moving now. Step by step i am re-animating this machine.

But it takes time.

Anyhow, thank you for your reply and if I do find some problems I will notify you.

Kind regards
Klaus P. Stock
