### ISSUE TITLE
User Defined Configuration

### ISSUE THREAD

**Issue by pentacular** [bdring/FluidNC#56]
**Please describe the feature you would like implemented**

The ability to include custom fields in the yaml configuration.

Maybe in some kind of custom field.

e.g.,

axis:
  x:
    custom:
      anchor:
        x: -240

etc

**Why do you think this would improve FluidNC?**

Code under Custom/ sometimes needs custom configuration.

**What do you need the feature for?**

I've just put together wall plotter custom kinematics in grbl esp32, and thought I'd see if I could port it across.

As part of this, I need to be able to configure the anchor points, which I previously did using a #define.

It seems like this is something that ought to be configurable, but I read in the wiki that unsupported keys will be dropped, which makes it sound currently impossible.

I can compile these fields directly into the Custom/wall_plotter.cpp, but that feels a bit like a regression.

**Do you know of other users who need this feature?**

No, but I can guess that most of the Custom/ code will want some kind of configuration support, otherwise it probably wouldn't be in Custom/ :).

**Comment by bdring** [comment]
We track bugs and basic features on a Trello board. We also have [this wiki page](https://github.com/bdring/FluidNC/wiki/Roadmap----What-isn't-done) with some basic TODO/roadmap items. We have most of our development discussions on [Discord server](https://discord.gg/qMVVmBua)

Kinematics is coming soon. Ideally many implementations like CoreXY are precompiled. We have been discussing new ways to implement it.  One thought is to have transform matrix option that could be setup in the config file. That would cover many types. More complicated ones would likely need to be compiled likeGrbl_ESP32.

**Comment by MitchBradley** [comment]
Since you appear to be a programmer, perhaps the best approach is not to wait for our efforts to modularize the kinematics and other customization points, but rather just add it however seems appropriate, guarded by ifdefs.  That will serve as information to guide us when we do get around to refining the customization architecture.

MotionControl.cpp in FluidNC is quite similar to Grbl_Esp32 apart from the homing, which was rewritten extensively.  The weak link hooks for kinematics are still present in the same form and usage.

Look at src/Custom/oled_basic.cpp for an example of adding custom code guarded by an ifdef.

To add a configuration section, look at src/Machine/MachineConfig.cpp: MachineConfig::group() and the variables like _start in src/Machine/MachineConfig.h

**Comment by pentacular** [comment]
Sounds good.

I'll open an issue specific to kinematics.
