### ISSUE TITLE
Feature:  M66 Command.

### ISSUE THREAD

**Issue by mac7988** [bdring/FluidNC#586]
### Machine Context

Custom bead machine.

### Feature Description

I was wondering if M66 can be implemented.

I want to index an Axis until a sensor is read the go to the next line of the gcode

### Other Approaches

Someone on discord suggested to use an external mcu to send dynanmic code via serial.

I think this makes it way to complex.

### How I Can Help

I can be provide funds for the time investment.

**Comment by bdring** [comment]
https://linuxcnc.org/docs/html/gcode/m-code.html#mcode:m66

I can add that to our dev issues tracker for future consideration.  It does not sound too complicated, but we are working on more basic things right now.

**Comment by mac7988** [comment]
> https://linuxcnc.org/docs/html/gcode/m-code.html#mcode:m66
> 
> I can add that to our dev issues tracker for future consideration. It does not sound too complicated, but we are working on more basic things right now.

Thank you

**Comment by mac7988** [comment]
Did you guys get a chance to look at this? Just wondering.

**Comment by bdring** [comment]
No, we are working on other things right now. This would have limited appeal, so there is no priority. Donations to the project are very low, so we have been working on our personal priorities.

This is a relatively simple command, but could have far reaching implications, like what state are you in while waiting. Hold is one option. If we feel we need a new state, that affects the WebUI and senders.

**Comment by bdring** [comment]
The "hold" state is simple, but does not work with the parameters.
```
P- - specifies the digital input number from 0 to 3.

E- - specifies the analog input number from 0 to 3.

L- - specifies the wait mode type.

Mode 0: IMMEDIATE - no waiting, returns immediately. The current value of the input is stored in parameter #5399

Mode 1: RISE - waits for the selected input to perform a rise event.

Mode 2: FALL - waits for the selected input to perform a fall event.

Mode 3: HIGH - waits for the selected input to go to the HIGH state.

Mode 4: LOW - waits for the selected input to go to the LOW state.

Q- - specifies the timeout in seconds for waiting. If the timeout is exceeded, the wait is interrupt, and the variable #5399 will be holding the value -1. The Q value is ignored if the L-word is zero (IMMEDIATE). A Q value of zero is an error if the L-word is non-zero.

Mode 0 is the only one permitted for an analog input.
```

**Comment by bdring** [comment]
The M0 command will put the machine in hold mode. Could the sensor be the resume button?

**Comment by mac7988** [comment]
I am trying to machine small parts that are indexing on a linear rail( not
part of your controller) I want to put a proximity sensor to start the
machining (fluidnc) when the sensor is active.

**Comment by MitchBradley** [comment]
Could this be done with an external microprocessor that sends feedhold/cyclestart bytes based on the sensor?

**Comment by hsyngndz85** [comment]
M66 konusunda gelişme varmı

**Comment by bdring** [comment]
We have M66 now.

http://wiki.fluidnc.com/en/features/supported_gcodes#m66-read-user-input

**Comment by emplast** [comment]
where can I find more information about analog or digital input and M-code M66
I mean coupling the value of either feed or Override with the sensor that goes into the Tinnybee board

**Comment by MitchBradley** [comment]
That is not possible directly within FluidNC.  You might be able to do it with an external MCU that communicates with Tinybee over a UART connected via the EXP connector.  The MCU would read a sensor and send override + and - realtime characters via the UART.

In the future, please do not re-use closed issues.

**Comment by emplast** [comment]
I assume communication via uart and via exp it is possible, you can do something more because it is supposed to control the speed or override, it would probably be easier via override because the whole machine can speed up or slow down the whole process in real timePiotr Majewski56-300 Milicz Polskaul. Kościuszki 48email: ***@***.***: +48 7883088939 sty 2025 21:32 Mitch Bradley ***@***.***> napisał(a):
That is not possible directly within FluidNC.  You might be able to do it with an external MCU that communicates with Tinybee over a UART connected via the EXP connector.  The MCU would read a sensor and send override + and - realtime characters via the UART.
In the future, please do not re-use closed issues.

**Comment by emplast** [comment]
is there a board where I can do this?Piotr Majewski56-300 Milicz Polskaul. Kościuszki 48email: ***@***.***: +48 7883088939 sty 2025 21:47 Piotr Majewski ***@***.***> napisał(a):I assume communication via uart and via exp it is possible, you can do something more because it is supposed to control the speed or override, it would probably be easier via override because the whole machine can speed up or slow down the whole process in real timePiotr Majewski56-300 Milicz Polskaul. Kościuszki 48email: ***@***.***: +48 7883088939 sty 2025 21:32 Mitch Bradley ***@***.***> napisał(a):
That is not possible directly within FluidNC.  You might be able to do it with an external MCU that communicates with Tinybee over a UART connected via the EXP connector.  The MCU would read a sensor and send override + and - realtime characters via the UART.
In the future, please do not re-use closed issues.

**Comment by Ams-Laser** [comment]
wil "M66 wait for input" be supported sometime ?
Thanks
